name: Pull Requests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  call-inclusive-naming-check:
    name: Inclusive naming
    uses: canonical/Inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "true"
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --all-extras
      - name: Install dependencies
        run: |
          uv pip install -r pyproject.toml --all-extras
      - name: Run static analysis
        run: make static
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --all-extras
      - name: Install dependencies
        run: |
          uv pip install -r pyproject.toml --all-extras
      - name: Run linters
        run: make lint
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --all-extras
      - name: Install dependencies
        run: |
          uv pip install -e . -r pyproject.toml --all-extras
      - name: Run tests
        run: make unit
